services:
  - type: web
    name: evensteven-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn evensteven.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: SECURE_SSL_REDIRECT
        value: True
    autoDeploy: false

databases:
  - name: evensteven-db
    databaseName: evensteven_db
    user: postgres
