# Generated by Django 5.2.4 on 2025-07-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_admin_group_currency_group_join_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='join_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
